// stories/de_bioscoop.js — StoryDef
// De bioscoop — F. Bordewijk

export default {
  id: 'de_bioscoop',
  title: 'De bioscoop',
  author: 'F. Bordewijk',
  year: 1919,
  genre: 'kort verhaal',
  fileCode: 'BC',
  writerStyle: 'sober en precies, psychologisch observerend, ironisch onderkoeld, realistische detaillering, elliptisch slot',
  sourceUrl: null,
  defaultStyle: { w1: 0.1, w2: 0.55, w3: 0.35, realism: 78 },

  worldRules: `WORLD RULES — apply unconditionally regardless of realism level:
• The story is set in mid-20th century Netherlands, primarily in The Hague and Leiden.
• Cold winter streets swept by an east wind at twelve degrees of frost, tram stops lit by pale streetlights, starlit ink-black skies.
• Architecture is urban Dutch bourgeois: terraced houses with front doors opening directly onto pavements, domestic interiors with armchairs, coffee cups, and folded newspapers.
• Characters wear heavy winter coats, scarves, and formal evening wear (tailcoats with insignia for student society members).
• Technology is pre-television: trams, taxis with running meters, rotary telephones, hazard lights just coming into use.
• The atmosphere alternates between warm lamp-lit domestic intimacy and the cutting, dusty cold of nocturnal city streets.
• FORBIDDEN: no anachronistic technology, no modern clothing or vehicles, no fantasy elements.`,

  chapters: [
    { id: 'ch1', title: 'Het vertrek' },
    { id: 'ch2', title: 'De lezing' },
    { id: 'ch3', title: 'De bioscoop' },
    { id: 'ch4', title: 'Het debat en de terugkeer' },
    { id: 'ch5', title: 'Het einde' },
  ],

  paragraphs: [
    { id: 1,  chapter: 'ch1', text: "'Ziezo, het wordt mijn tijd,' zei Landes. De klok wees bijna zeven. Hij dronk zijn bodempje koffie, stond op, legde de krant neer en kuste Nora vluchtig op de wang. 'Het wordt wel weer nachtwerk, dus jullie gaan maar naar je bed.'" },
    { id: 2,  chapter: 'ch1', text: "'Zal je je vooral goed inpakken en opletten op straat?' vroeg ze. 'Je bent dikwijls zo verstrooid.'" },
    { id: 3,  chapter: 'ch1', text: "Paula keek even naar hen terwijl haar zuster haar zwager zijn kus teruggaf. Ja, het was van haar kant gemeend, evenzeer als haar waarschuwing. Ze hield toch wel degelijk van haar man, zelfs nu, zelfs deze avond waarop het wel weer mis zou gaan. Altijd voelde Paula bij zulk een afscheid een zekere beklemming. Aan de anderen ontging haar blik. Zijzelf zei alleen: 'Neem toch eindelijk eens een taxi, met die beestachtige kou.'" },
    { id: 4,  chapter: 'ch1', text: "Hij schudde afwijzend. 'Je weet dat ik daar niet aan begin. Als ik de laatste tram mocht missen, dan misschien, in godsnaam, maar nu zeker niet.'" },
    { id: 5,  chapter: 'ch1', text: 'De voordeur sloeg dicht. Een wolk stof joeg door de straat. Het was al de tweede dag van een oosterstorm bij twaalf graden vorst, maar Landes had er zich tegen gewapend, de tramhalte lag slechts een paar minuten verder en lijn tien bracht hem tot voor het station.' },
    { id: 6,  chapter: 'ch1', text: "Hij was aan een groot dagblad verbonden als criticus voor poëzie en had een jaar geleden een aantal artikelen, bijgeschaafd en wat uitgebreid, gebundeld onder de verzamelnaam: Geen Zoïlus. Zijn eigen motto gaf over die titel enige verklaring: 'Ik spaar niemand. Voor mij bestaat er geen schrijver. Een boek bestaat er voor mij wel. Maar een boek is niet iemand, het is een inhoud. En een knappejongen die een inhoud sparen kan. Ik niet.'" },
    { id: 7,  chapter: 'ch1', text: 'Of het door zijn bundel kwam, - maar in elk geval kreeg hij meer en meer aanzoeken voor een avondcauserie, door het hele land heen. Zijn oordeel was scherp, en tevens eerlijk. Gelijk zovelen werd hij aan schrijftafel of katheder een ander mens in wie men de zachtzinnige huisman, de man zonder de geringste achtergedachten, niet zou herkennen. Hij kon geestig zijn, maar hij werd nooit persoonlijk; dat lag reeds in zijn motto vast. Wat puntigheid betreft van stijl en ontleding bleef Busken Huet zijn grote voorbeeld; hij kon het zonder buitenlanders stellen.' },
    { id: 8,  chapter: 'ch2', text: 'Deze avond zou hij in Leiden spreken voor het litterair studentendispuut Colloquium Doctum, en wel over de nieuwste poëzie van het Nederlandse taalgebied dat noordelijk België, Zuid-Afrika, de Nederlandse Antillen en Suriname insloot. Studenten vormden zijn liefste gehoor. Daar stond hij niet tegenover een gezelschap dat inert zàt, daar werd van weerskanten gespeeld, daar klonk het echte colloquium op, met openhartige vragen, antwoorden, redengevingen, zonder reserve. Zoals voor hem niet de schrijver gold, slechts het boek, zo gold voor dat publiek niet de spreker, slechts het gesprokene.' },
    { id: 9,  chapter: 'ch2', text: 'Op het Stationsplein in Leiden dacht hij alweer niet over een taxi. Dure ritten, en dan nog een flinke fooi ook. Hij was misschien zuinig, maar hij kon er niet tegen dat een chauffeur zuinig in zijn hand keek. Hij was bang dat zijn fooi nooit groot genoeg zou wezen. Allemaal incidenten en complicaties. Uit de bussen hier werd hij niet zo gauw wijs. Hij ging lopen en het was ook niet ver. De oostenwind doorsneed een holle stad. De sterren stonden staalhard in een diepzwarte hemel, zó zwart - je kon je niet voorstellen dat die nog eens blauw zou worden. Wervelende wolken stof bestookten hem telkens met naaldpunten. Maar hij was ruim op tijd binnen.' },
    { id: 10, chapter: 'ch2', text: 'Twee bestuursleden wachtten hem op aan de wijd open poort, blootshoofds, in rok, met insignes. Ze toonden een beetje verwondering dat hij niet voor rekening van het dispuut aan het station een taxi had genomen. Hij liet dat zo. In een kleine kamer ontvingen hem de overigen. Daar was ook een hoogleraar die kwam luisteren.' },
    { id: 11, chapter: 'ch2', text: 'Te precies acht uur ging men in optocht naar de grote zaal, achter in het gebouw, eerst de praeses, dan hij in zijn gewone pak, dan het overige bestuur weer in gala. De zaal was heel goed bezet. Hier telde niet de tegenkanting van de natuur. Een echt fijne belangstelling, dacht hij, gaande tussen de rijen lange gestalten, meisjes en mannen, plotseling opgerezen en plotseling doodstil. Hij kende dit soort ontvangst, toch ontroerde het hem weer even.' },
    { id: 12, chapter: 'ch2', text: "Achter de katheder met de versterker zag Landes ver weg ook de hoogleraar die, niet in de stoet meegekomen, een bescheiden plaats had gekozen, aan het einde van de rij. Na het welkomstwoord tot hem gericht ving hij aan: 'Meneer de praeses en heren verdere bestuursleden van Colloquium Doctum, hooggeleerde heer, dames en heren, - ik kom tot mijn onderwerp via een algemene inleidende stelling over kunst, een stelling die niet gauw te vaak herhaald kan worden en die, juist nu we zullen spreken over de nieuwste en zo beweeglijke, nerveuze poëzie, me goed van pas lijkt. Het is dit: alle kunst is in wezen statisch. En dat valt te eerder op nu de wetenschap, en zeker in bepaalde takken, een dynamiek vertoont als nooit tevoren. Maar de kunst, in zijn verschillende takken, blijft door dit alles wezenlijk onbewogen. Kunst is gefixeerd, van de aanvang af. Daar zijn ontdekkingen niet bij mogelijk. Kunst is uiting van het gemoed en het gemoed is onveranderlijk.'" },
    { id: 13, chapter: 'ch3', text: "Een half uur na Landes ging Nora van huis, tegen haar zuster zeggende: 'Ik ga naar de bioscoop.' Ze had dat al vaak gezegd, maar in plaats van eerst de verlegenheid, later de onaandoenlijke blik bij deze voor de vorm gesproken woorden zag Paula die zwijgend opkeek ditmaal in Nora's ogen iets dat haar beklemming vergrootte. Het was anders dan opwinding, het wees eerder op een offerande, zelfs op verheerlijking daarvan. En weer sloeg de voordeur dicht." },
    { id: 14, chapter: 'ch3', text: "Nora had, sinds een paar jaar wel, een verhouding. Wie 'hij' was wist Paula niet, maar het was een getrouwde man met kinderen, wiens vrouw nooit zou willen scheiden. Als Landes elders een avondlezing had ging Nora doorgaans 'naar de bioscoop' en Paula mocht niet mee. Bij de tweede weigering met een hoogrode kleur doorzag Paula het. Behoedzaam ondervraagd gaf Nora, geen volleerde leugenaarster, de verhouding ook toe, maar hield zich verder vaag. Volgens haar 'gebeurde er nooit iets, zoenen, nu ja'. Het was mogelijk, want, dacht Paula, overspel is voor een Nederlandse vrouw geen eenvoudige zaak. Aan de andere kant ging het komediespelen Nora, als vrouw van welke nationaliteit ook, tegenover de echtgenoot uitstekend af. Ook deed het gemak waarmee ze haar verboden gangen gaan kon haar allengs de schroom tegenover de echtgenoot verliezen. Soms kondigde ze, aan tafel met hun drieën, aan dat ze die avond een bioscoopje wou pakken. Ze vertelde later vaak iets over de nietgeziene film. Paula vatte dat 'hij' de film dan tevoren gezien had, - een voor de hand liggende truc. En omdat Paula zelf vrouw was verwonderde haar deze komedie van haar zuster, de eigen avond nog, of, zo ze al naar bed waren gegaan, daags daarop aan het ontbijt gespeeld, niet al te zeer. Ze deed op de duur zelf mee, weliswaar geprest door de omstandigheden." },
    { id: 15, chapter: 'ch3', text: 'Want wat moest ze anders doen? Klikken? Haar beste zwager ongelukkig maken? Haar zuster van wie ze toch bleef houden? Haar eigen leven in dit huis opgeven? Niet tellen dat Nora toch ook goed voor haar man was, zorgzaam? Ontrouw sluit zorg voor de echtgenoot evenmin uit als trouw die zorg insluit; zo eenvoudig is de mens niet, dacht ze. Ze gingen soms met hun drieën naar de bioscoop, of samen als hij geen lust had en thuisbleef. Het was alles doodnormaal. Maar dan moest er ook bij tijden gelogen worden. Dus heette het wel eens dat ze met Nora was meegeweest, dan had op haar beurt Nora haar tevoren ingelicht en kreeg de enkelvoudige truc meervoudige toepassing.' },
    { id: 16, chapter: 'ch3', text: 'Nora tot betere gedachten brengen had ze allang opgegeven. Dit was geen gril, maar pure hartstocht.' },
    { id: 17, chapter: 'ch3', text: "Paula, ook een vrij jonge en heel knappe vrouw, werd op straat meermalen lastig gevallen. Eens enterde haar een lichtelijk aangeschoten losbol met de woorden: 'Wat zoudt u denken van het onvermijdelijke?' Het was geen aanloop tot een polemiek over de wereldondergang; ze begreep het. Rap gaf ze ten antwoord: 'Ik denk dat het tòch vermeden moet worden,' en liet hem staan. Ze nam het hem helemaal niet euvel. Hij lachte. Sindsdien dacht ze vaak in die term wanneer het de verhouding van Nora met de onbekende betrof, maar dan wel allerminst in een luchthartige stemming, - integendeel. Zou het onvermijdelijke eens gebeuren? Was het gebeurd? Haar zwager koesterde niet het minste wantrouwen. Maar waar was het einde?" },
    { id: 18, chapter: 'ch4', text: "Te precies negen uur werd er voor een twintig minuten gepauzeerd. In gezelschap van de praeses naar de koffiekamer gaande zei Landes: 'Nu komt er wat ik voor mezelf het interessantste vind, het debat.' 'O, u zult heel wat vragen te horen krijgen, reken maar. En uw tijd?' 'Dat zou ik van de omstandigheden willen laten afhangen... Het is me nogal eens gebeurd dat ik een hotel moest nemen.' 'Dat kan ook hier als u het mocht willen.' 'Nee, dank u. Er gaan nog genoeg late treinen naar Den Haag. Ik heb een ruime keus.' 'Zoals u wenst. Alleen zou ik u aan het slot nog even willen bedanken, een paar minuten maar. En,' voegde de praeses er glimlachend bij, 'u bent al komen lopen en u hebt toch minstens recht op een taxi terug... En nu nog graag even uw gironummer.'" },
    { id: 19, chapter: 'ch4', text: "De hoogleraar kwam aan hun tafeltje zitten. Er ging koffie rond. Toen keek Landes op zijn horloge. 'Het is nu negen dertien. Wat vindt u? Zullen we maar doorgaan?' Hij liet uitleg achterwege. De praeses gaf een wenk en even later luidde de bel. De hoogleraar verontschuldigde zich voor de rest van de avond. Landes stond weer op het podium en de zaal liep haastig vol." },
    { id: 20, chapter: 'ch4', text: 'Het debat was gevarieerd en getuigde van intelligentie. Landes nam er aan deel met zijn gewone strijdlust. Hij hield echter de vragen kort en zo waren ook zijn antwoorden. Nog vóór tienen kondigde hij aan dat nu de laatste vraag aan de beurt was en even na tienen had de praeses de bijeenkomst met een woord van dank gesloten.' },
    { id: 21, chapter: 'ch4', text: "Onder het doorlopen van het gangpad in dezelfde sfeer van plechtigheid als waarmee hij ontvangen was, maar die hem nu ontging, zei Landes tegen de praeses: 'Ik zou toch wel graag gebruik maken van uw aanbod van een taxi. Met een beetje geluk ben ik dan om elf uur thuis.'" },
    { id: 22, chapter: 'ch4', text: 'De praeses, blootshoofds in zijn frak waarvan de lange panden in een stofwolk om zijn benen fladderden, opende en sloot voor de gast het portier. De trein vertrok op tijd. In Den Haag bracht een taxi onder de stationskap Landes naar zijn woning. Het was toen elf uur.' },
    { id: 23, chapter: 'ch5', text: 'Hoe zou het aflopen, waar was het einde? had Paula zo vaak gedacht, bevreesd, beklemd, en ook gedeeltelijk bewust van eigen schuld. Nu was het dan afgelopen. En hoe. Dit was het einde.' },
    { id: 24, chapter: 'ch5', text: 'De taxi stopte voor een wijd open voordeur en een stralend verlichte gang daarachter. Door die gang kwam een man in winterjas haastig aangestapt, gevolgd door een vrouw in mantel. Landes zag niets, niet dokter Kramer, niet krijtwitte Paula. De rug naar zijn huis gekeerd stond hij af te rekenen, maar op een onbegrijpelijke manier kon hij uit zijn geld niet recht wijs worden.' },
    { id: 25, chapter: 'ch5', text: "'Wacht u nog even, chauffeur, we hebben de wagen dadelijk weer nodig,' zei achter Landes een stem die hem ontging. Een resolute arm nam hem mee, een eindje de straat in. Toen beiden terugkwamen steunde deze arm de weduwnaar krachtig. De huisdokter duwde hem op de achterbank, ging naast hem zitten en wenkte Paula naar haar plaats bij de chauffeur." },
    { id: 26, chapter: 'ch5', text: "Paula wist één ding. Ze mocht niet uitbarsten, niet huilen zelfs. Dat kwam allemaal later. De woorden van het ziekenhuis klonken in haar oren na. 'Toen ze binnen werd gebracht ademde ze nog,' had de telefoon gezegd. Vreselijker woorden waren er niet denkbaar, en even was haar een paniekstemming overvallen. Nora aangereden op de Laan van Meerdervoort terwijl ze bij rood licht een zebra overstak. Nora dood en zij alleen in huis. Toen belde ze in uiterste nood hun dokter, enkele huizen verderop in de straat. Hij zou dadelijk met haar meegaan, maar zijn knipperlichten werkten niet. Ze moesten een taxi nemen. Ze liet de voordeur open, want ze had zich al reeds enigszins herwonnen. Hij vond haar, gekleed, een briefje krabbelend voor haar zwager: 'Nora in ziekenhuis Zuidwal. Heel ernstig. Paula.' Even later hield er een wagen stil. Ze meenden beiden dat het de bestelde was, maar het was Landes die thuiskwam. Nog een geluk bij een ongeluk, dacht dokter Kramer." },
    { id: 27, chapter: 'ch5', text: 'En nu reden ze naar het ziekenhuis, in een loeiende wind, over uitgestorven straten, door stofwolken die de chauffeur telkens noopten de ruitenwissers te gebruiken. Hij zei niets. Hij begreep uit het zwijgen dat deze rit iets betrof waarbij geen gesprek paste.' },
    { id: 28, chapter: 'ch5', text: "De dokter hield Landes' arm stevig in de zijne. Diens enige reactie was een aanhoudend onbedwingbaar trillen, van het hele lichaam. Paula kon niet beletten dat haar tranen stroomden, geluidloos. Toen werd haar verdriet overtopt door angst. Wat, als haar zwager uit zijn versuffing ontwaakte? En reeds stond het te gebeuren. De dokter merkte dat het armtrillen ophield, en een klankloze stem uit de diepte van de wagen zei haperend, zacht, toch duidelijk: 'Hoe kwam ze op straat?'" },
    { id: 29, chapter: 'ch5', text: "Paula keerde zich niet om. Ze moest tijd winnen en vroeg: 'Wat zei je?' Het armtrillen was opnieuw begonnen. Niet Landes, maar de dokter herhaalde de vraag. En ineens wist ze het antwoord, doodsimpel, volstrekt aannemelijk, een antwoord dat de vraag haar zelf had gesuggereerd: 'Ze was naar de bioscoop.' En vlak daarop voegde ze er aan toe: 'Ze was naar Metropole, naar West Side Story.'" },
    { id: 30, chapter: 'ch5', text: 'Of dit tot Landes doordrong wist ze niet. Eerst enkele dagen later zag ze in hoe in zekere zin gelukkig, ja bijna ontzondigend dit wanhoopsantwoord was geweest. Want niet alleen dat die film daar werd vertoond, maar ook lag de fatale oversteekplek zowel dicht bij de bioscoop als in de normale route naar huis. En nog weer later bleek de leugen niet slechts gedekt door de plaats van het ongeval, doch ook door de tijd. Want de film bezat een lang eerste gedeelte en het ongeval gebeurde toen het daar pauze was. De bioscoop, soms een leugenvenster, altijd een luchtspiegeling, hier een uitredding. En haar antwoord een stuk kristal, smetteloos, fonkelend, ondoorzichtig. Het ideale antwoord.' },
    { id: 31, chapter: 'ch5', text: 'In het ziekenhuis bracht dokter Kramer beiden naar een wachtlokaal. Hijzelf ging dieper het gebouw in. Paula die haar tranen bedwongen had keek nu en dan naar haar zwager. Ze duwde hem zacht op de bank, maar hij stond dadelijk weer overeind. Hij stond maar, hij begon te klappertanden, hij trilde en soms werd het schudden. Hij was onder de rit zo veranderd dat ze er haar eigen grote verdriet bijna door vergat en zich in ontzetting afvroeg of hij wel ooit kon worden als vroeger. Bij stoten klonk in het kamertje het droge ratelen van zijn gebit. Hij zei niets en zij zei niets. Hij keek dof naar de grond.' },
    { id: 32, chapter: 'ch5', text: "'De dokter was algauw terug. 'U kunt uw vrouw op het ogenblik niet zien, meneer Landes. Morgenmiddag, laten we zeggen om vier uur, komt u dan beiden.' Hij was zelf geschrokken. Het bekken totaal versplinterd. Er zou maar een klein deel van haar gezicht toonbaar zijn, morgen. En een mooie vrouw geweest. De zuster had een glas water in de hand en een tablet. Landes slikte gehoorzaam." },
    { id: 33, chapter: 'ch5', text: "Of hij deze woorden begreep kon Paula evenmin zeggen. Maar haar klonken ze net zo ijzingwekkend in de oren als de telefonische boodschap: 'Toen ze binnen werd gebracht ademde ze nog.'" },
    { id: 34, chapter: 'ch5', text: 'Landes was na een halfjaar over de slag heen. Thuis als regel een stil mens kon hij nu aanvankelijk niet over Nora zwijgen, al repte hij van het ongeval zelf maar zelden, en ook dan begaf hij zich niet in bijzonderheden, nooit. Hij was niet ergdenkend van aard, hoe kon hij het dan in dit geval zijn? Nora was uitgegaan bij storm en felle vorst, zeker, maar hij ook. Nora had hem voor zijn verstrooidheid gewaarschuwd, nu was ze zelf een ogenblik roekeloos geweest. Geen mens hield zich voortdurend in zijn macht, en dit gevolg, hoe verschrikkelijk ook, vloeide toch alleen voort uit het risico dat het leven van heden meebracht. Zo moest hij het zien, zo zag hij het, zo zei hij het aan zijn schoonzuster, tweemaal. En verder ging hij in zijn gesprekken over Nora terug tot hun verleden. Hij recapituleerde liefst zijn huwelijk.' },
    { id: 35, chapter: 'ch5', text: "Toch had Paula zich gewapend voor alle mogelijkheden. Ze moest als uitgangspunt de leugen in de taxi nemen, die uitlegging aan haar zwager gegeven onderweg naar de Zuidwal. En die leugen bleek als 't ware tot waarachtigheid geschapen. Met de hoofdfilm, West Side Story, werd haast onmiddellijk aangevangen. De pauze trad circa tien uur in. Nora was vlakbij de bioscoop overreden, zowat om tien uur tien. In aanmerking genomen het werk voor politie en geneeskundige dienst, kon het ziekenhuis Paula eerst tegen elven inlichten. Dat Nora haar dood was tegemoet gegaan, niet komende van Metropole, maar van elders, zou nooit te bewijzen zijn. Een vermoeden in die richting was op zichzelf al praktisch onbestaanbaar en ook voor de politie zonder belang. Buiten de juridieke sfeer, dus voor haar zwager, was de reconstructie weliswaar nog niet voltooid, maar ze kon zich van hem toch geen andere vraag denken dan deze: hoe Nora zo tussentijds vertrokken was. Hier evenwel lagen de antwoorden juist voor het grijpen. Mogelijk beviel de film haar niet of was hij haar te lang. Of ze voelde zich niet helemaal wel. Of ze had hoofdpijn. Of bij de ontzettende winterkou op straat verlangde ze eenvoudig vroeg naar huis." },
    { id: 36, chapter: 'ch5', text: 'Met dat al stelde hij die vraag niet, tenminste niet aan haar. Hij zou hem nooit stellen. Hij was en bleef zonder enig wantrouwen, dermate dat hij zichzelf al een antwoord moest hebben gegeven: weliswaar zou niemand dat ooit weten, maar hij had natuurlijk dezelfde redenen voor het tussentijds terugkeren overwogen die zij, Paula, voor hem gereed hield. Het geval sloot aldus hermetisch en zou te eeuwigen dage sluiten.' },
    { id: 37, chapter: 'ch5', text: "Hier lagen niet Paula's moeilijkheden. Ze wist ook dat, indien het toch nog geëist werd, ze haar uitgebreide, veelvoudige leugen met gemak, verstand, behendigheid zou voordragen. Maar wat haar drukte en waar haar zwager van vrij bleef, dat was de noodzaak om te verzwijgen, zij het om beider bestwil, wat volgens haar rotsvaste overtuiging had plaatsgegrepen. Want ze vergat niet die blik van haar zuster bij het heengaan, afwijkend van anders, een blik van opwinding, een woordeloze en toch voor wie lezen kon overduidelijke aankondiging dat de tijd van het nog betrekkelijk onschuldige 'zoenen, nu ja' voorbij was. Nora zou zich die avond geven, wellicht had ze het 'hem' niet met zoveel woorden beloofd, maar zich geven zou ze." },
    { id: 38, chapter: 'ch5', text: "Aldus lagen Paula en haar zwager op dit punt mijlenver uiteen. Want voor haar was de dood van Nora geen gevolg van funeste onachtzaamheid, maar van wat er tussen 'hem' en 'haar' gebeurd was. Van een ongeval in de gewone betekenis kon er geen sprake zijn en Landes verkeerde in dwaling. Nora was allerminst roekeloos van aard. Maar als Nederlandse vrouw voelde ze zich zwaar zondig en, dat bleek nu, haar aard bracht haar tot een boete in de meest extreme vorm. Nora had gehandeld of uit vertwijfeling of uit verbijstering. Ze wilde niet langer bestaan of ze bestond reeds niet meer. Mogelijk had ze na de daad ervaren dat ze van 'hem' niet hield." },
    { id: 39, chapter: 'ch5', text: 'Paula kende de slotsom van haar zwager: de mens van heden had het gevaar op de weg in zijn leven verdisconteerd zoals de mens van alle tijden deed met zijn werken, eten, slapen. De mens was eenvoudig zijn gevarenkring gaan uitbreiden en zuiver reflexief zijn reactie daarop. Zo werd het dodelijke verkeersongeval een ontijdige dood als een andere.' },
    { id: 40, chapter: 'ch5', text: 'Paula moest wel de conclusie van haar zwager primitief vinden, kinderlijk bijna, maar alleen omdat ze meer wist en meer had gezien. Daardoor waren de eerste weken voor haar moeilijker dan voor hem. Aan de andere kant was de verhouding tussen zusters minder innig dan tussen echtgenoten. Overigens, hoe dat wezen mocht, ook bij haar sleet op de duur de speciale verschrikking van deze dood, gelijk alles slijt.' },
    { id: 41, chapter: 'ch5', text: 'Eén punt bleef er voor Paula nog onopgelost. Hoe kwam haar zwager die avond zo vroeg thuis? Ze zou er nooit naar vragen, maar hijzelf gaf onvoorzien de verklaring. Ze leefden allang rustig in de oude verhouding verder. Het bestaan had zich gevoegd. Zij deed het huishouden voor beiden, hij had zijn recensies en zijn spreekbeurten. Ook zou er van zijn boekje een tweede druk verschijnen.' },
    { id: 42, chapter: 'ch5', text: "En toen, op een avond, terwijl ze bij de thee vreedzaam tegenover elkaar de krant lazen, aan de kleine ronde tafel, onder de schemerlamp, zei hij en legde het dagblad neer: 'Het is vandaag juist een jaar geleden.' Iets van die aard had ze de hele dag al verwacht, maar ze zou er niet over beginnen. Nu sprak hij er dan toch van en ze antwoordde: 'Ja, dat weet ik. Ik heb er ook aan gedacht.'" },
    { id: 43, chapter: 'ch5', text: "Hij scheen het al een poos achter zijn krant te hebben overwogen, want hij vervolgde: 'Weetje wat het vreemde is?... Ik realiseer het me nu eigenlijk pas goed... Eerst zeg ik die avond tegen jullie dat ik zeker niet vóór twaalven terug ben, maar in Leiden maak ik veel haast... Ik kan mijn gedrag nog helemaal reconstrueren... Om negen uur pauzeren we voor een twintig minuten, maar ik zorg er voor dat ik binnen het kwartier alweer achter mijn lessenaar sta. Aan de voorzitter van het dispuut zeg ik in de pauze dat voor mij het eigenlijk aardige pas begint met het debat, zo straks, en dat het daarmee soms nachtwerk wordt, en even later regel ik het zo dat mijn hele optreden om tien uur is afgelopen. Ze doen me een taxi cadeau, dat laat ik daar, maar in Den Haag neem ik een taxi voor mijn rekening, terwijl ik aan taxi's een gloeiende hekel heb. Ik had gerust op de tram kunnen wachten. En zo ben ik om elf uur thuis. Enfin, dat weetje... Maar nu het vreemde: ik heb geen gejaagdheid gevoeld, geen onrust, niets. Ik heb niet eens gevoeld dat ik naar huis moest. Ik ben eenvoudig een automaat geweest... Noem het een voorgevoel, mij best, maar dan toch een waarvan geen sprankel tot mijn bewustzijn is doorgedrongen. Dat is dan weer een van de abstrusiteiten in het leven.'" },
    { id: 44, chapter: 'ch5', text: "'Ja,' beaamde Paula, 'dat moet het wel geweest zijn, een voorgevoel.' Maar ze dacht alreeds in een andere richting. Of hij zich van zijn haast nu bewust was geweest of niet, - och, dat liet haar eigenlijk koud. Haar vlug verstand trok uit het verhaalde een heel andere slotsom. Ze had de faits et gestes van Nora allang opgelost. Nu gaf haar zwager haar de oplossing van de zijne en het was ronduit een openbaring. Ze zag zich opeens in een timmerwinkel, ze rook de stoffige zaagselgeur, ze voelde haar voeten bedolven door houtkrullen, maar... daar lag die gladde glanzende plank, spiegelglad geschaafd. Ze werd compleet losgetrokken van haar omgeving, maar het beeld, ongerijmd, hallucinatoor, hoogst ongewoon, bijna litterair, was waarheid in zijn kern. Hier kon geen sprake wezen van een voorgevoel, een uur voordat de ramp plaatsgreep. Nora werd haar man ontrouw, tot de bodem toe ontrouw tijdens die pauze in Leiden. Hij had daar een tijdsein ontvangen. Het was niet doorgedrongen tot zijn begrip. Toch had het hem aangeraakt en een reflex veroorzaakt op zijn psychische trommelvliezen. De kring was ook hier gesloten." },
    { id: 45, chapter: 'ch5', text: "Haar eigen reflex was dat haar zwager in haar ogen steeg om zoveel fijnheid van organisme. Ze steeg in eigen ogen ook zelf. En Nora daalde. Nora, een lieve vrouw die met haar leven geboet had voor een misstap, maar die toch ook het 'onvermijdelijke' bij twee mannen had leren kennen. Niet overmatig intelligent trouwens, die zuster van haar. En zij, Paula, zonder man, zonder avontuur, al was 't waar dat ze alle aanzoeken had afgewezen omdat ze lastig en kritisch was en superieur... Maar nu... maar nu...? Zou het niet op de duur...? Ze was nog pas vijfendertig... Zouden niet al heel wat van hun kennissen denken dat...? En hoe heette het ook weer...? Absolutie...? Nee, dat klonk rooms... Vergunning? Nee, dat was drank en tabak... Komaan, ze wist het woord toch wel...? Dispensatie, daar had ze het... Maar misschien was zoiets niet eens nodig, in dit geval. Ze kende de wet niet." },
    { id: 46, chapter: 'ch5', text: "Hij zat weer achter zijn stuk krant. Peinzend? Ze zag de twee lege koppen. En ze dacht: met mij niet het 'onvermijdelijke', nooit. Resoluut stond ze op." },
    { id: 47, chapter: 'ch5', text: "'Zeg, ik zou er maar niet te veel over doordenken... En wil je nog niet een kopje thee? Ik wel. En neem jij nu eindelijk ook eens een tweede kop. Dat is toch veel gezelliger.'" },
  ],
};
