// stories/meneer_pem_heeft_een_droom.js — StoryDef
// Meneer Pem heeft een droom — Anoniem

export default {
  id: 'meneer_pem_heeft_een_droom',
  title: 'Meneer Pem heeft een droom',
  author: 'Anoniem',
  year: null,
  genre: 'overig',
  fileCode: 'PD',
  writerStyle: 'droog-realistisch, psychologisch nauwkeurig, ironisch-afstandelijk, gedetailleerde karakterschets, sobere verteltoon, licht surrealistische climax',
  sourceUrl: null,
  defaultStyle: { w1: 0.2, w2: 0.3, w3: 0.5, realism: 62 },

  worldRules: `WORLD RULES — apply unconditionally regardless of realism level:
• SETTING: occupied Amsterdam, 1940–1942. Streets are grey-brown, overcast, blacked-out at night — no bright artificial light anywhere. Well-fed, sharply-uniformed German soldiers and women in expensive fur coats contrast against drab, threadbare Dutch civilians.
• PEM — ONE single consistent appearance for the ENTIRE story. Do NOT invent separate "young"/"old" or "early-war"/"late-war" versions — only about two years pass and his appearance never changes: a slight, gaunt civil servant past sixty, hollow-cheeked, pale ashen complexion, thin grey-brown hair slicked flat, always dressed in a dark grey wool overcoat and dark charcoal trousers — deliberately colourless and unremarkable.
• PEM'S WALKING STICK: from the story's opening through §9, Pem is never seen without a plain dark wooden walking stick — it is as much a part of his silhouette as his overcoat. At §9 he abruptly stops carrying it (his trembling fists are clenched inside his coat pockets instead), and from that point onward — including the entire dream sequence — the stick is PERMANENTLY and conspicuously absent.
• THE BROCKEN DREAM: a vast, windless, crystalline-clear summer panorama seen from the rocky Brocken summit, overlooking the North German Plain. Pem stands utterly alone — no other human figure is ever present on the peak.
• THE DREAM TANKS — treat as a second, major non-human "character", described with the same exactness as Pem: colossal elliptical vehicles, 1000 metres long × 500 metres high × 500 metres wide, with a smooth, gleaming, beetle-shell-black hull curving down and inward at its lower edge. The entire outer surface is built from countless independently-articulating tracked segments that ripple and flow over the hull like a single rolling skin. They move with slow, ponderous, unstoppable momentum — ploughing through rivers, forests and cities alike, leaving behind deep, wide troughs of pulverised rubble that slowly fill with dark water. No exhaust, smoke or fire is ever emitted by the tanks themselves — only the dust and rubble thrown up by their passage. Late in the dream a fleet of twenty to thirty of these tanks carries the hammer-and-sickle flag mounted across their backs.
• SCALE AND VIEWPOINT: the dream is shown from a great elevated distance — towns and cities appear only as small, irregular flesh-pink patches on a green plain; human crowds appear only as anonymous, faceless swarms seen from far above, never as individuals.
FORBIDDEN: Pem's walking stick in any scene from §9 onward; any colour or warmth in Pem's clothing; any family members, friends or romantic companions near Pem; visible individual faces in crowds; modern vehicles, post-1945 architecture or contemporary signage; detailed, accurate Nazi insignia.`,

  chapters: [
    { id: 'ch1', title: "Meneer Pem heeft een droom" },
  ],

  paragraphs: [
    { id: 1, chapter: 'ch1', text: "Sommige mensen conformeren zich aan hun naam, en tot hen behoorde meneer Pem, een even droog en zielloos in verschijning als zijn geslachtsnaam in klank. Hoewel vaal van tint was hij nooit ziek, want daartegen beschermde hem zijn droog gestel. Het zielloze was hem eigen als ambtenaar die nooit een fout beging." },
    { id: 2, chapter: 'ch1', text: "Want meneer Pem was gemeenteambtenaar in de hoofdstad; hij naderde de pensioengerechtigde leeftijd reeds aardig toen in mei 1940 stad en land werden bezet. Hij deed zijn ambtelijke plicht voor en na. In den beginne had hij gezeten op een met leer beklede kruk aan een schuins gedachte lessenaar, later zat hij in een stoel achter een plat bureau, maar altijd bleef hij zijn werk doen in hetzelfde ongastvrije lokaal, en hij was er van lieverlede een meubelstuk geworden dat zich nergens elders op zijn plaats voelde dan daar, en dat niemand zich op een andere plek kon denken. Dit soort ambtenaar, liever inboedelstuk, is zeldzaam geworden, indien al niet verdwenen, maar het bestond nog in 1940, zij het mogelijk slechts in de persoon van meneer Pem. Hij droeg ook een passende voornaam; hij heette enkel Piet, zelfs niet Pieter, maar Piet, sec. Piet Pem, het kon niet kleurlozer." },
    { id: 3, chapter: 'ch1', text: "Hij had als vrijgezel kamers in de Plantage, en hij kwam vandaar en ging daarheen te voet, en met een stok onder alle weersgesteldheid. Hij behoefde niet heel ver te lopen. In al zijn ambtelijke jaren had hij zich slechts tweemaal bezondigd aan een reisje tijdens vakantie. Hij was naar de Harz geweest, en had er vertoefd in een klein eenvoudig hoteldorp achter de Brocken. Vandaar had hij op een keer de Brocken beklommen, maar een ijskoude kruiende mist benam hem het beroemde uitzicht vanaf de bergkoepel, en na even droefgeestig te hebben gerust in een enorm houten bouwsel, waarop hele zingende colonnes uit de natte nevel kwamen toegemarcheerd, terwijl de hoge zalen weergalmden van schoenspijkers en liederen, begeleid door het gerinkel van bierglazen, keerde hij dit rumoer de rug toe, en kwam er die zomer niet weer." },
    { id: 4, chapter: 'ch1', text: "Het volgende jaar beproefde hij het nogmaals, deels uit volharding, deels uit gebrek aan fantasie, was toen zo gelukkig bij stralende zon het grootse panorama op de Noord-Duitse Laagvlakte te aanschouwen, en oordeelde daarmee aan zijn hoogste wens voldaan. Sedertdien bracht hij zijn vakantie door in de hoofdstad zelf. Vermits hij heel sober leefde waren er slechts twee mogelijkheden: ofwel hij speculeerde, ofwel hij spaarde. Het laatste was het geval, en aangezien hij geen enkel familielid telde, geen enkele vriend of vriendin, en zijn fantasie niet reikte tot het maken van een testament waarin zijn nalatenschap zou worden bestemd voor een aangewezen doel, zou uiteindelijk de Staat der Nederlanden van meneer Pem erven. Dat liet hem koud, want hij spaarde niet om het geld, maar enkel om het sparen." },
    { id: 5, chapter: 'ch1', text: "Toen de oorlog van 1940 uitbrak was meneer Pem uiteraard de minst bewogen figuur op de bureaukamer die hij met anderen deelde. Hij bepaalde zich tot aanhoren, jaknikken, en was de eerste die aan het werk ging, maar niemand verdacht hem van misplaatste sympathieën. Hij werd algemeen voor een goed vaderlander gehouden, eenvoudig omdat men nooit iets van misplaatste sympathie had bespeurd, krachtens het beginsel dat aan de mens eigen is en door de wet overgenomen: goede trouw wordt ondersteld, kwade trouw moet worden bewezen." },
    { id: 6, chapter: 'ch1', text: "Nu was meneer Pem inderdaad een goed vaderlander in die betekenis dat hij geen slecht vaderlander mocht heten. Maar zijn goede vaderlandershap viel te definiëren als een gedesinteresseerd vaderlanderschap. De misplaatste sympathieën hinderden hem niet, omdat hij er niet over nadacht. Hij bezat geen politieke overtuiging en liet er zich geen opdringen. Zijn aard echter neigde naar behoud van de bestaande orde, en dus stemde hij op de een of andere partij die hij aanzag voor behoudend. Dat dit moeilijk werd toen alle partijen zich als vooruitstrevend aandienen ontging hem niet, doch hij bleef zijn best doen in zijn rode stip op het stembiljet zijn behoudendheid tot uitdrukking te brengen." },
    { id: 7, chapter: 'ch1', text: "De oorlog schreed voort met een razende dynamiek die ons land echter vooreerst niet beroerde, tenzij indirect, door allerlei beperkende maatregelen, waarvan het voorschrift van verduistering dadelijk zeer hinderlijk werd. En al waren wij nog niet vervallen tot eigenlijke honger, schaarste en rantsoenering grepen toch steeds verder om zich heen." },
    { id: 8, chapter: 'ch1', text: "Toen ontwaakte in meneer Pem een haat tegen de Duitsers, aangewakkerd door het feit dat hij hen op straat overal ontmoette, in uniformen waaruit hij niet wijs werd, of zonder uniform, maar steeds kenbaar aan weldoorvoedheid, gebruinde trekken, onberispelijke kleding en schallende stemmen vol sisklanken. Vroeger had hij dat niet zo opgemerkt. Nu beledigden die mannen zowel zijn oog als zijn oor. Hun vrouwen liepen met de kostbaarste bontmantels, van beginnende herfst tot diep in de lente. Hij vergeleek dat alles niet met zijn landgenoten, hij dacht maar aan zijn eigen persoon, en hij haatte." },
    { id: 9, chapter: 'ch1', text: "Allangs klom zijn haat zo hoog dat hij zulk een Duitser graag een slag met zijn wandelstok had gegeven. Er waren ogenblikken dat hij vreesde voor zichzelf, want hij besefte heel goed dat het antwoord de kogel zou zijn. Toen zag men hem op zijn bureau voor het eerst verschijnen zonder stok. Hij had zijn bevende vuisten onderweg in zijn jaszakken begraven gehouden." },
    { id: 10, chapter: 'ch1', text: "In deze tijd werd meneer Pem zelfs voor een zéér goed vaderlander aangezien, want de deportaties waren begonnen, en in zijn bureaukamer heerste de grootste opwinding. Eén woord van protest uit zijn anders zo zwijgzame mond bezat tienmaal zoveel waarde als een stroom woorden uit de monden der overigen. Het maakte grote indruk op hen, maar zij wisten niet dat hij in zijn verontwaardiging een uitlaat vond voor zijn persoonlijk onrecht: hij was ook te verstandig om daarvan blijk te geven. Intussen, mensenroof, was dat au fond wegens het ongerief: hij moest nu weer — o nieuwe ellende! — een grote omweg maken van zijn huis in de Plantage Middenlaan naar zijn bureau, want hij mocht niet meer door de Jodenbuurt, en dat terwijl hij zich nog altijd niet had leren aanpassen aan het lopen zonder stok." },
    { id: 11, chapter: 'ch1', text: "Het was in de tijd toen de Duitsers hun vlag hadden geplant op de Elbroes. De toestand leek hopeloos voor elk rechtgeaard vaderlander, en voor meneer Pem evenzeer. Zijn verschiet wemelde van gehate uniformen, onrechtmatig verkregen bontmantels, en zwarte handelaren die hij nooit zou benaderen omdat het sparen hem boven alles ging. En toen had hij zijn droom, — hij die nooit had gedroomd, zelfs niet bij de grootste innerlijke opwinding." },
    { id: 12, chapter: 'ch1', text: "Hij stond op de Brocken en hij keek uit over de Laagvlakte. Een heerlijke zomerdag, windstil, een strakblauwe hemel, en hij alleen. Het groen der aarde overheerste zover zijn oog kon reiken, maar hier en daar was het belegd met kleine veelvormige lappen of flarden van lichtroze vleeskleur, geen twee eender. Dat waren de dorpen en de steden. Rechts in de verte zag hij dicht bij de horizon een heuvel die daar bij zijn weten niet hoorde, want hij pikeerde zich zelfs dromend een goed aardrijkskundige te zijn, tenminste van de streek die hij indertijd op de kaart had bestudeerd. Nee, daar in het noordoosten paste geen heuvel, en zeker geen van zo vreemde vorm en kleur, een platte zwarte koepel die naar onderen inboog." },
    { id: 13, chapter: 'ch1', text: "Meneer Pem was evenwel te onrustig om zijn aandacht bij een enkel object te bepalen. Hij wist dat Duitsland in oorlog was, en hij speurde naar bewijzen, maar hij ontdekte niets, geen rook, geen vlammen, geen ruïnen, en het was zo stil dat men een speld had kunnen horen vallen op de rotsgrond die hem droeg. Weer dwaalde zijn blik naar het noordoosten, en waarlijk, hij zag nu duidelijk op diezelfde verre plek van de vreemde heuvel rook hangen, grauw en zwartachtig en daartussen wolken leemgeel stof. Was het misschien in plaats van een heuvel een enorm gebouw geweest dat ontploft was en waarvan hij nou aanstonds de knal horen zou? In elk geval betekende dit oorlog. Hij herademde. Hij was in het land van de vijand en dat land kreeg nu eindelijk op zijn huid. Maar even later trof de vreemde heuvel opnieuw zijn oog, meer westelijk. En het bleek geen heuvel, want het bewoog nu, weliswaar kruipend, maar dat moest het gevolg zijn van de afstand." },
    { id: 14, chapter: 'ch1', text: "Voordat meneer Pem ook maar iets had kunnen gissen omtrent het wonder dat zich in de verte afspeelde werd hij gewikkeld in een wereld van verbijstering. Want met een afgrijselijk gehuil dook om een hoek van het Harzgebergte een zwart gevaarte op, zo dichtbij dat zijn blik het niet kon omvatten, zo onmeetbaar reusachtig dat het eerste wat hij dacht was: de maan is omlaaggevallen! Tegelijk golfde de grond als door een aardbeving, en terwijl hij zelf in een rukwind plat vooroverviel hoorde hij achter zijn rug nog het knetterend instorten van de verlaten houten hotels op de Brockenkoepel. Hij sprong overeind, maar het verschijnsel was reeds verdwenen." },
    { id: 15, chapter: 'ch1', text: "Meneer Pem kreeg niet de tijd de verwoestingen die het gedrocht op zijn weg had aangericht in ogenschouw te nemen, want intussen was er iets binnen zijn gezichtsveld gekomen dat, zonder het raadsel op te lossen, zich althans enigszins liet bepalen. Het was soortgelijk aan de vreemde heuvel, in de verte, dicht bij de horizon ontwaard, maar het bevond zich op een afstand van naar schatting niet meer dan hoogstens tien kilometer van hem af, en het bewoog zich met grote vaart door de vlakte, daar in de diepte. In de diepte? Niet precies, want het was zo hoog, zo breed, zo lang, dat hij er, hier op zijn standplaats, niet op neerkeek, maar tegenaan — een rollende berg, rond, in ellipsvorm, met de glansen van een zwart keverschild, en zo zwaar dat zijn gewicht zich voortplantte naar de wortels van de Brocken en vandaar in sidderingen tot hem opsteeg." },
    { id: 16, chapter: 'ch1', text: "Hij zag nu ook, begiftigd met een ongelooflijk scherp gezichtsvermogen, wat er ginds gebeurde. Daar lag een plek in lichte vleeskleur, een kleine stad, maar de berg rolde aan en rolde over de stad als een wals over een wegdek. De hele stad scheen opeens bedekt. Het begon daar te roken, en even zag hij iets van vlammen langs de bodem spelen, nietig. Door de ontwikkeling van het rookgordijn kon hij algauw slechts glimpen van de berg waarnemen die over de plek heen en weer ging als een strijkijzer over een kledingstuk, en daarbij allengs wegzonk, voor een deel tenminste. Toen klom de berg uit de afgrond en rolde verder. Maar het oog van meneer Pem keerde zich naar het verwoeste stadje. Het gaf zijn plaats slechts aan door een enorme stofwolk die langzaam van de aarde losraakte. En onder de wolk zag hij een diepe ronde kuil liggen en van het stadje niets meer. Het was fijngestampt en weg in de bodem die zich reeds begon te vullen met water dat kwam en hij wist niet waarvandaan." },
    { id: 17, chapter: 'ch1', text: "Meneer Pem voelde zich op het punt te gaan jubelen, toen hij uit het oosten - het leek wel in slagorde op grote afstand van elkaar een reeks van dergelijke bergen zag nader komen, rollende in westelijke richting. En ofschoon er nog veel onverklaard bleef wist hij reeds dit: de Russen! Zij kwamen voor de grote vergelding, - met hun bergen. Hij stond als behoudend mens van nature nogal achterdochtig tegenover al wat Russisch was, tenminste sinds 1917, maar in een droom is alles toegelaten, en meneer Pem slaakte een kreet, sprong op en rende de noordkant van de Brocken omlaag, de bevrijding tegemoet. Hoe hij er daarbij in slaagde het niemandsland, aan zijn voeten geschapen door het tweede, slechts in een flits geziene monster, te overwinnen kan alleen worden verklaard doordat meneer Pem een keus deed uit de overvloed van originele transportmiddelen die de droom tot onze beschikking houdt." },
    { id: 18, chapter: 'ch1', text: "Kort en goed, hij bevond zich het volgende ogenblik in zulk een tank, want tanks waren het, oorlogswapens waartegen niets bestand was, die de strijd zouden beëindigen door hun enkele zwaarte. Stalen gevaarten van duizend meter lang, vijfhonderd meter hoog en evenzoveel meter breed, - de maat genomen over hun grootste doorsneden. Rivieren, meren bestonden niet voor hen, zij gingen erover als een wagenwiel over een straatgoot; moerassen en veenstreken evenmin, zij ploegden zich erdoorheen, steunend op de vaste bodem, al mocht deze een paar honderd meter diep liggen onder de onvaste. Zij konden zich ook ver wagen in de zeeën, maar daar lag niet hun taak. Slechts de steilste toppen van het hooggebergte bleven voor hen ontoegankelijk; daar echter hadden zij evenmin te maken." },
    { id: 19, chapter: 'ch1', text: "Meneer Pem, gekenmerkt door nauwgezetheid, deed zich nu als belangstellend medereiziger door een schimmig blijvende gids alles haarfijn uitleggen. De mantel van deze tanks bestond uit een aantal onafhankelijk van elkaar werkende rupsbanden, en was dus als het ware één gecumuleerd rad, dat vooruit en achteruit kon gaan, hellingen beklimmen en afdalen, ook zwenken, opzijvallen en over de kop duikelen. Onder deze rusteloos kabbelende opperhuid bevond zich het stalen pantser, en weer daarbinnen een bol die in verdiepingen op elkaar getast een gehele fabrieksstad bevatte, met elektrische centrales, kolenbunkers, water- en oliereservoirs, machinerieën voor de aandrijving, lokaliteiten voor sportbeoefening, en zo meer. Er was zelfs een kleine bioscoopzaal, waar tot geruststelling van het behoudende element in meneer Pem slechts gekeurde films mochten worden vertoond. De afgewerkte gassen werden binnen de stad zelf vernietigd. Zuurstof uit cilinders onderhield de vuren. Door gaten, uitgespaard in het pantser tussen de rupsbanden, kwam de lucht binnen die de mens nodig heeft om te ademen, zoals de lucht door de mijnschacht neervalt in de mijn. Daar echter dient de verbruikte lucht te worden verwijderd, hier werd zij verwerkt. En water, dat ook wel eens even binnengolfde, werd weggepompt." },
    { id: 20, chapter: 'ch1', text: "De fabrieksstad moest een bolvorm bezitten omdat hij anders binnen het elliptische pantser niet de horizontale stand had kunnen bewaren, noodzakelijk voor onbelemmerde werking ook bij de vreemdste capriolen van het tanklichaam. De bol bezat van onderen een eigen zwaartepunt. Hij was door kogellagers vrijgehouden van het pantser, en in zekere zin zweefde hij daarbinnen. De drijfstroom werd via de kogels overgebracht op de pantserhuid en vandaar op de rupsbanden." },
    { id: 21, chapter: 'ch1', text: "Deze schets is een onbeholpen weergave, waarbij moet worden bedacht dat meneer Pem natuurkundige noch mechanicus was. Zou het anders zijn geweest, dan was hij in zijn onbeschrijfelijke opwinding toch aan bijzonderheden voorbijgegaan. Het was niet de tijd om na te denken, maar alleen om op te nemen. Hij stond ergens tegen de binnenwand van de bol gedrukt die hier en daar kijkgaten bevatte van glas. Het wiegelen of deinen ter wille van het evenwichtsbehoud was nauwelijks voelbaar, hoe snel hij ook soms bij hellingen in alle richtingen het pantser door hem zag langsstromen. Kwam een van de luchtgaten voor zijn blik, dan had hij een uitzicht, beperkt weliswaar en kortstondig. Eerst keek hij recht vooruit, maar daar zag hij van de verwoesting naar zijn smaak veel te weinig. Alleen begonnen huizen, fabrieksschoorstenen, kerktorens voor zijn ogen reeds van verre in te storten door de enkele dreunende nadering. Algauw begreep hij meer baat te zullen vinden bij een blik achterwaarts. Hij rende dus naar die kant - hij deed er ongeveer vijf minuten over -, en inderdaad, zijn moeite werd ditmaal beter beloond. Want al ging alles ook hier schuil in vlammen, rook en vooral veelkleurig flets stuifsel, hij kon toch in het eerste spoor van zijn voertuig iets overschouwen van een verbrijzeling, dermate snel, grondig en uitgestrekt dat, toen hij later kennis kreeg van de oppervlaktebombardementen op de Duitse steden, hij ze kinderwerk vond, althans voor zichzelf, want hij sprak niet over zijn droom." },
    { id: 22, chapter: 'ch1', text: "Naar achteren kijkend zag hij een diep, honderden meters breed dal van het fijnste puin, waarin geen enkel materiaal meer te herkennen viel. Dan minderde zijn tank de vaart, bewoog naar weerskanten, rees en daalde als een hobbelpaard, en de vergroting van het vernietigingsveld deed hem dan de vlammen zien, links en rechts opspringend van de vore waarbinnen alles was verstikt. Het geheel ging echter dadelijk onder in reusachtige rook- en stofkalkbuilen." },
    { id: 23, chapter: 'ch1', text: "Toen vond hij een kijkgat in een zijwand, en omdat hier bol en pantser elkaar tot de kleinste afstand genaderd waren had hij een verhoudingsgewijs ruim uitzicht in de flitsen dat er voor zijn ogen een luchtgat gleed. Zijn hart sprong op, want wat hij nu met horten en stoten zag was grandioos. Zijn tank moest behoren tot een slaglinie, en zich bevinden in het Roerdistrict. Hier zag hij niet zijn eigen werk, maar dat van tien of twaalf zustermachines, rondwaaiend als een ruitenwisser vanaf zijn voetpunt, als een regiment om zijn as, langzaam een vulkaantrechter vormend met een straal van tientallen kilometers en herschapen in een werkzame vulkaan, in een caldera van vlammentongen, van as en puin, toen de leviathans van het vasteland aan de zelf opgeworpen trechterwanden omhoogkropen." },
    { id: 24, chapter: 'ch1', text: "En de tanks rolden voort. Dan is er weer een hiaat. Het kan wezen dat meneer Pem in zijn droom een uiltje heeft geknapt. Hij herinnert zich wel iets van een grote rivier - hij denkt aan de Rijn - waarin hij een tank zag staan als een dam in snel stijgend water dat de landerijen deed overstromen. En hij weet zeker dat het vervolgens pal oostwaarts ging, niet naar het land van oorsprong terug, nee, naar die hemorroïde in 's werelds rectum (deze metafoor is van meneer Pem zelf in zijn droom, maar daar in zuiver Nederlands uitgedrukt), naar Berlijn in het Duitse Rijk. En hier gingen de tanks, twintig, dertig stuks, meer niet, maar elk van 1000 bij 500 bij 500 meter, - hier ging dat pantseregiment dat niet wezenlijk kon worden beschadigd door zelfs het zwaarste geschut of de zwaarste luchttorpedo, - hier ging deze rollende verschrikking in een cirkel, walsend de zee van steen, een reuzenstad enerzijds, aan de andere kant een speelgoedstad. Voor zijn ogen voltrok zich het uitradiëren met een feilloze systematiek: de cirkelgang der tanks werd een spiraal die toeliep op een middelpunt. En meneer Pem die tot dusver geen enkel levend wezen had mogen zien zag hier vanuit zijn hoogte de mensen in enorme kudden. Want een miljoenenstad kan niet in uren worden ontruimd. Meneer Pem zag het wegens het langzame werktempo en met verscherpte zintuigen uitnemend. De ware lekkerbek haast zich niet met zijn maal, en deze tanks waren lekkerbekken. Hij hoorde enkel het zwakke zoemen in de fabrieken aan alle kanten rondom hem, boven en beneden. En wat hij zag was van zijn hoogte uit niet het detail, het was de algemene lijn, de grote lijn. De parken verdwenen zoals eerder de bossen waren verpletterd. De mierenzwermen die zich bewogen over de nog gespaard gebleven straten verdwenen met huizenrijen en boomalleeën onder de tanks, en daarna was er niets meer, geen spoor, alles, leven en dood, scheen eenvoudig opgelikt." },
    { id: 25, chapter: 'ch1', text: "Maar tegelijk dreef dit onbeschrijfelijke oorlogstuig door zijn zich steeds vernauwende spiraalgang, binnen een zich steeds verdiepende trechter, de bevolkingsresten naar het planimetrisch centrum, en toen de tanks tot daar waren genaderd vormden zij om de laatste radeloze mierenkoek opnieuw een cirkel, de wijze van een kudde wilde olifanten die over de geheime dansplaatsen in het oerwoud zijn verpletterende carrousel rijdt. Maar de ruggen van deze mechanische, monumentale ondieren waren plotseling tienduizendvuldig bestoken met de vlag van hamer en sikkel." },
    { id: 26, chapter: 'ch1', text: "Dit was het laatste wat meneer Piet Pem zag, en zijn voldoening ging zo diep, hij nam het hamer-en-sikkelsymbool eenvoudig op de koop toe. En toen hij ontwaakte uit zijn droom voelde hij zich allerminst een teleurgesteld hervinder van een grauwe en uitzichtloze werkelijkheid. Want hoewel hij niemand deelgenoot maakte van zijn droom en integer voor de buitenwereld degeen bleef voor wie hij doorging - een goed vaderlander die bij buien lucht zocht in termen van verontwaardiging over de algemene toestand -, was hij vanaf dat ogenblik innerlijk overtuigd dat Duitsland zou verliezen, door tanks of welke wapenen ook. Maar verliezen zou het. En Nederland kwam weer vrij, dat wil zeggen hij, Piet Pem, kwam weer vrij." },
    { id: 27, chapter: 'ch1', text: "Zo gebeurde het. Wat Nederland betreft weten wij het allemaal, al was het dan niet door Russische tanks van 1000 bij 500 bij 500. En wat meneer Pem betreft wordt het hier meegedeeld. Wij mogen hem niet hard vallen, dunkt me, om zijn zelfzucht en zijn gedesinteresseerd vaderlanderschap. Dat is nu eenmaal verbonden aan het celibaat, vooral indien het bezwaard is met een ambtenaarsfunctie en met het uitzicht (men zou haast willen zeggen bezwaard met een servituut van uitzicht) op spoedige pensionering. Nee, laten wij meneer Pem niet misprijzen en ons liever verwonderen dat zulke ongehoord wilde fantasieën konden opkomen in het brein van een dor mannetje, al was het dan ook in de droom - zijn enige -, en vervolgens de conclusie trekken dat het eigenlijke wonder hierin is gelegen dat er voor de droom geen dorre mannetjes bestaan." },
  ],
};
